CREATE USER fileuser WITH PASSWORD '12345';
GRANT ALL PRIVILEGES ON DATABASE filedb TO fileuser;
GRANT ALL PRIVILEGES ON SCHEMA public TO fileuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fileuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fileuser;